# Generated by Django 6.0.3 on 2026-03-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('tablet', 'Tablet'), ('headphones', 'Headphones'), ('smartwatch', 'Smartwatch'), ('camera', 'Camera'), ('desktop', 'Desktop'), ('other', 'Other')], max_length=50)),
                ('icon', models.CharField(default='', max_length=10)),
                ('badge', models.CharField(blank=True, max_length=30)),
                ('badge_type', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('specs', models.JSONField(default=dict)),
                ('highlights', models.JSONField(default=list)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
